-- 管理员 AI 接口配置：全量内容 AES-GCM 加密，独立版本防止并发覆盖。
CREATE TABLE IF NOT EXISTS ai_model_settings (
    id BIGINT NOT NULL PRIMARY KEY,
    encrypted_config MEDIUMTEXT NULL,
    version BIGINT NOT NULL DEFAULT 1,
    updated_by BIGINT NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
