package com.gameplay.common.exception;

import lombok.Getter;

/**
 * 全局错误码枚举。
 *
 * <p>主体来自《详细设计说明书》6.1 全局错误码枚举；
 * 末尾补充 auth 登录/注册流程必需的业务错误码（设计文档未列出）。</p>
 */
@Getter
public enum ErrorCode {

    // ===== 认证与令牌 =====
    AUTH_TOKEN_MISSING(401, "AUTH_TOKEN_MISSING", "未提供认证令牌"),
    AUTH_TOKEN_INVALID(401, "AUTH_TOKEN_INVALID", "认证令牌无效或过期"),
    AUTH_TOKEN_VERSION_MISMATCH(401, "AUTH_TOKEN_VERSION_MISMATCH", "账号登录状态已失效"),
    AUTH_ACCOUNT_DISABLED(403, "AUTH_ACCOUNT_DISABLED", "账号已被禁用"),
    AUTH_PASSWORD_CHANGE_REQUIRED(403, "AUTH_PASSWORD_CHANGE_REQUIRED", "首次登录或重置后必须修改密码"),

    // ===== 权限 =====
    PERMISSION_DENIED(403, "PERMISSION_DENIED", "无功能访问权限"),
    PERMISSION_DATA_SCOPE_DENIED(403, "PERMISSION_DATA_SCOPE_DENIED", "无数据访问权限"),
    PERMISSION_AI_WRITE_FORBIDDEN(403, "PERMISSION_AI_WRITE_FORBIDDEN", "AI不具备业务写权限"),

    // ===== 订单与档期 =====
    ORDER_NOT_FOUND(404, "ORDER_NOT_FOUND", "订单不存在"),
    ORDER_STATUS_INVALID(409, "ORDER_STATUS_INVALID", "订单当前状态不允许该操作"),
    ORDER_ALREADY_PAID(409, "ORDER_ALREADY_PAID", "订单已支付"),
    ORDER_PAYMENT_EXPIRED(409, "ORDER_PAYMENT_EXPIRED", "订单支付已超时"),
    ORDER_ACCEPT_EXPIRED(409, "ORDER_ACCEPT_EXPIRED", "订单接单已超时"),
    ORDER_SELF_BOOKING_FORBIDDEN(422, "ORDER_SELF_BOOKING_FORBIDDEN", "不能预约自己的服务"),
    ORDER_START_TIME_INVALID(409, "ORDER_START_TIME_INVALID", "未到允许开始服务的时间"),
    SLOT_CONFLICT(409, "SLOT_CONFLICT", "预约时段冲突"),
    SERVICE_NOT_AVAILABLE(422, "SERVICE_NOT_AVAILABLE", "服务当前不可预约"),
    COMPANION_NOT_AVAILABLE(422, "COMPANION_NOT_AVAILABLE", "陪玩师当前不可接单"),

    // ===== 钱包与幂等 =====
    WALLET_BALANCE_INSUFFICIENT(422, "WALLET_BALANCE_INSUFFICIENT", "虚拟余额不足"),
    WALLET_LEDGER_DUPLICATE(409, "WALLET_LEDGER_DUPLICATE", "资金流水重复"),
    WALLET_CONCURRENT_MODIFICATION(409, "WALLET_CONCURRENT_MODIFICATION", "钱包并发更新，请重试"),
    IDEMPOTENCY_KEY_CONFLICT(409, "IDEMPOTENCY_KEY_CONFLICT", "幂等键与请求不匹配"),

    // ===== 客服 =====
    CS_CONVERSATION_NOT_FOUND(404, "CS_CONVERSATION_NOT_FOUND", "客服会话不存在"),
    CS_CONVERSATION_CLOSED(422, "CS_CONVERSATION_CLOSED", "客服会话已关闭"),
    CS_CONVERSATION_ALREADY_CLAIMED(409, "CS_CONVERSATION_ALREADY_CLAIMED", "会话已被其他客服领取"),
    CS_AGENT_NOT_ONLINE(422, "CS_AGENT_NOT_ONLINE", "客服未在线或不可接待"),
    CS_AGENT_CAPACITY_EXCEEDED(422, "CS_AGENT_CAPACITY_EXCEEDED", "客服接待会话数已达上限"),
    CS_MESSAGE_DUPLICATE(409, "CS_MESSAGE_DUPLICATE", "客服消息重复"),
    CS_TRANSFER_REQUIRED(422, "CS_TRANSFER_REQUIRED", "当前问题需要转人工处理"),

    // ===== AI =====
    AI_SERVICE_UNAVAILABLE(503, "AI_SERVICE_UNAVAILABLE", "AI服务暂不可用"),
    AI_RESPONSE_UNTRUSTED(422, "AI_RESPONSE_UNTRUSTED", "AI回答置信度不足"),

    // ===== 通用 =====
    VALIDATION_FAILED(400, "VALIDATION_FAILED", "请求参数校验失败"),
    SYSTEM_ERROR(500, "SYSTEM_ERROR", "系统内部错误"),

    // ===== 以下为 auth 业务补充（详细设计 6.1 未列出，登录/注册流程必需） =====
    AUTH_CREDENTIAL_INVALID(401, "AUTH_CREDENTIAL_INVALID", "账号或密码错误"),
    ACCOUNT_NOT_FOUND(404, "ACCOUNT_NOT_FOUND", "账号不存在"),
    ACCOUNT_USERNAME_EXISTS(409, "ACCOUNT_USERNAME_EXISTS", "用户名已被占用"),
    ACCOUNT_MOBILE_EXISTS(409, "ACCOUNT_MOBILE_EXISTS", "手机号已被占用"),
    ACCOUNT_EMAIL_EXISTS(409, "ACCOUNT_EMAIL_EXISTS", "邮箱已被占用"),
    AUTH_PASSWORD_INCORRECT(401, "AUTH_PASSWORD_INCORRECT", "原密码不正确"),

    // ===== 目录基础数据（游戏/服务类型/标签，FR-M10~M12） =====
    GAME_NOT_FOUND(404, "GAME_NOT_FOUND", "游戏不存在"),
    GAME_NAME_EXISTS(409, "GAME_NAME_EXISTS", "游戏名称已存在"),
    SERVICE_TYPE_NOT_FOUND(404, "SERVICE_TYPE_NOT_FOUND", "服务类型不存在"),
    SERVICE_TYPE_NAME_EXISTS(409, "SERVICE_TYPE_NAME_EXISTS", "服务类型名称已存在"),
    SERVICE_TYPE_CODE_EXISTS(409, "SERVICE_TYPE_CODE_EXISTS", "服务类型编码已存在"),
    TAG_NOT_FOUND(404, "TAG_NOT_FOUND", "标签不存在"),
    TAG_EXISTS(409, "TAG_EXISTS", "同一游戏同一分类下标签名称已存在"),

    // ===== 陪玩师入驻与主页（FR-P01~P06） =====
    COMPANION_APPLICATION_NOT_FOUND(404, "COMPANION_APPLICATION_NOT_FOUND", "入驻申请不存在"),
    COMPANION_APPLICATION_ALREADY_PENDING(409, "COMPANION_APPLICATION_ALREADY_PENDING", "已有待审核的入驻申请"),
    COMPANION_ALREADY_APPROVED(409, "COMPANION_ALREADY_APPROVED", "您已是陪玩师，无需重复申请"),
    COMPANION_APPLICATION_NOT_PENDING(409, "COMPANION_APPLICATION_NOT_PENDING", "该申请不在待审核状态"),
    COMPANION_PROFILE_NOT_FOUND(404, "COMPANION_PROFILE_NOT_FOUND", "陪玩师资料不存在"),
    COMPANION_NOT_APPROVED(403, "COMPANION_NOT_APPROVED", "入驻申请未通过，无法使用陪玩师功能"),
    COMPANION_PROFILE_SUSPENDED(422, "COMPANION_PROFILE_SUSPENDED", "陪玩师资格已被暂停"),
    COMPANION_SERVICE_NOT_FOUND(404, "COMPANION_SERVICE_NOT_FOUND", "服务项目不存在"),
    COMPANION_SERVICE_NOT_APPROVED(409, "COMPANION_SERVICE_NOT_APPROVED", "服务尚未通过审核，无法上架"),
    COMPANION_SERVICE_REJECTED(409, "COMPANION_SERVICE_REJECTED", "服务项目审核未通过，请修改后重新提交"),
    COMPANION_SERVICE_INVALID_PARAM(422, "COMPANION_SERVICE_INVALID_PARAM", "服务项目参数不合法"),
    AVAILABILITY_NOT_FOUND(404, "AVAILABILITY_NOT_FOUND", "档期记录不存在"),
    AVAILABILITY_TIME_INVALID(422, "AVAILABILITY_TIME_INVALID", "档期时间不合法"),
    AVAILABILITY_DELETE_FORBIDDEN(409, "AVAILABILITY_DELETE_FORBIDDEN", "该档期已有订单占用，不能删除"),

    // ===== 评价与投诉（FR-U15~U19、FR-M08/M09/M18/M19） =====
    REVIEW_NOT_FOUND(404, "REVIEW_NOT_FOUND", "评价不存在"),
    REVIEW_ALREADY_EXISTS(409, "REVIEW_ALREADY_EXISTS", "该订单已评价，每个订单只能评价一次"),
    REVIEW_ORDER_NOT_ELIGIBLE(422, "REVIEW_ORDER_NOT_ELIGIBLE", "只有本人已完成的订单可以评价"),
    COMPLAINT_NOT_FOUND(404, "COMPLAINT_NOT_FOUND", "投诉不存在"),
    COMPLAINT_ALREADY_EXISTS(409, "COMPLAINT_ALREADY_EXISTS", "该订单已有进行中的投诉"),
    COMPLAINT_ORDER_NOT_ELIGIBLE(422, "COMPLAINT_ORDER_NOT_ELIGIBLE", "当前订单状态不支持发起投诉"),
    COMPLAINT_STATUS_INVALID(409, "COMPLAINT_STATUS_INVALID", "投诉不在可处理状态"),
    COMPLAINT_REFUND_AMOUNT_INVALID(422, "COMPLAINT_REFUND_AMOUNT_INVALID", "退款金额必须大于0且不超过订单金额"),
    COMPLAINT_TYPE_INVALID(422, "COMPLAINT_TYPE_INVALID", "投诉类型不合法"),

    // ===== 文件存储（4.7 文件与审计） =====
    FILE_TOO_LARGE(413, "FILE_TOO_LARGE", "文件大小超出限制"),
    FILE_TYPE_NOT_ALLOWED(415, "FILE_TYPE_NOT_ALLOWED", "文件类型不允许"),
    FILE_EMPTY(400, "FILE_EMPTY", "上传文件为空"),
    FILE_NOT_FOUND(404, "FILE_NOT_FOUND", "文件不存在"),
    FILE_PATH_INVALID(400, "FILE_PATH_INVALID", "文件路径不合法"),

    // ===== 客服账号（FR-C01~C06） =====
    CS_ACCOUNT_NOT_FOUND(404, "CS_ACCOUNT_NOT_FOUND", "客服账号不存在"),
    CS_ACCOUNT_EXISTS(409, "CS_ACCOUNT_EXISTS", "客服账号名已存在"),
    CS_ACCOUNT_STATUS_INVALID(409, "CS_ACCOUNT_STATUS_INVALID", "客服账号状态不允许该操作"),

    // ===== 客服会话与消息（FR-C07~C29） =====
    CS_CONVERSATION_NOT_CLOSED(422, "CS_CONVERSATION_NOT_CLOSED", "会话尚未关闭，不能评价"),
    CS_ALREADY_EVALUATED(409, "CS_ALREADY_EVALUATED", "该会话已评价"),
    CS_CONVERSATION_VERSION_CONFLICT(409, "CS_CONVERSATION_VERSION_CONFLICT", "会话已被其他客服处理，请刷新"),
    CS_CONVERSATION_STATUS_INVALID(409, "CS_CONVERSATION_STATUS_INVALID", "会话当前状态不允许该操作"),

    // ===== AI 知识库（FR-C23） =====
    KNOWLEDGE_NOT_FOUND(404, "KNOWLEDGE_NOT_FOUND", "知识条目不存在"),
    KNOWLEDGE_TITLE_EXISTS(409, "KNOWLEDGE_TITLE_EXISTS", "同一分类下问题标题已存在"),

    // ===== 站内通知与公告（FR-A07/A08、FR-M13） =====
    NOTIFICATION_NOT_FOUND(404, "NOTIFICATION_NOT_FOUND", "通知不存在"),
    ANNOUNCEMENT_NOT_FOUND(404, "ANNOUNCEMENT_NOT_FOUND", "公告不存在"),
    ANNOUNCEMENT_STATUS_INVALID(409, "ANNOUNCEMENT_STATUS_INVALID", "公告状态不允许该操作"),

    // ===== 收藏（FR-U06） =====
    FAVORITE_ALREADY_EXISTS(409, "FAVORITE_ALREADY_EXISTS", "已收藏该陪玩师"),
    FAVORITE_NOT_FOUND(404, "FAVORITE_NOT_FOUND", "收藏记录不存在"),
    FAVORITE_COMPANION_INVALID(422, "FAVORITE_COMPANION_INVALID", "只能收藏审核通过的陪玩师");

    private final int httpStatus;
    private final String code;
    private final String message;

    ErrorCode(int httpStatus, String code, String message) {
        this.httpStatus = httpStatus;
        this.code = code;
        this.message = message;
    }
}
